version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.5-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_PASSWORD=test
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
      - '8336:3306'
  moodle:
    image: 'docker.io/bitnami/moodle:3-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_PASSWORD=test
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
  camunda:
    image: 'swimdhbw/camunda:latest'
    ports: 
      - '8081:8080'
    restart: always
    environment:
    - PROCESS_DB_HOST=mariadb:3306
    - PROCESS_DB_USER=bn_moodle
    - PROCESS_DB_PWD=test
    volumes:
      - 'camunda_data:/camunda/deployments'
      - 'C:\Users\NHG\Documents\DHBW\3. Studienjahr\SWIM-Projekt\Code\scientific-paper-camunda-application-for-paper\application_for_paper_start\target\application_for_paper.war:/camunda/webapps/application_for_paper.war'
      - 'C:\Users\NHG\Documents\DHBW\3. Studienjahr\SWIM-Projekt\Code\scientific-paper-camunda-application-for-paper\digitalsignature\target\digitalsignature.war:/camunda/webapps/digitalsignature.war'
  master-data-api:
    image: 'swimdhbw/swim-master-data-api:latest'
    environment:
      - HOST_URL='http://localhost'
    ports:
      - '8082:9090'
    restart: always
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
  camunda_data:
    driver: local
